from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agentport.models import PortPlan


def write_gitagent_repo(plan: PortPlan) -> list[str]:
    output = plan.output_path
    output.mkdir(parents=True, exist_ok=True)
    generated: list[str] = []

    def write(rel: str, text: str) -> None:
        path = output / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text.rstrip() + "\n", encoding="utf-8")
        generated.append(rel)

    write("agent.yaml", _agent_yaml(plan))
    write("SOUL.md", _soul(plan))
    write("RULES.md", _rules(plan))
    write("DUTIES.md", _duties(plan))
    write("memory/MEMORY.md", _memory(plan))
    write("workflows/ported-identity-review.yaml", _workflow(plan))
    write("knowledge/source-framework.md", _source_knowledge(plan))

    written_tool_slugs: set[str] = set()
    for idx, tool in enumerate(plan.extraction.tools, start=1):
        name = _slug(tool.name or f"tool-{idx}")
        if name in written_tool_slugs:
            continue
        written_tool_slugs.add(name)
        write(f"tools/{name}.yaml", _tool_yaml(tool))

    if plan.extraction.identity_fragments:
        write("skills/ported-identity/SKILL.md", _identity_skill(plan))

    conversion = {
        "source": str(plan.source_path),
        "framework": plan.framework.__dict__,
        "compatibility_profile": plan.compatibility.__dict__ if plan.compatibility else None,
        "docs_evidence": plan.docs_evidence.__dict__ if plan.docs_evidence else None,
        "generated_agent": plan.name,
        "identity_fragments": [fragment.__dict__ for fragment in plan.extraction.identity_fragments],
        "rules": [fragment.__dict__ for fragment in plan.extraction.rules],
        "model_preferences": [fragment.__dict__ for fragment in plan.extraction.model_preferences],
        "tools": [tool.__dict__ for tool in plan.extraction.tools],
        "manual_review": plan.extraction.manual_review,
        "crewai_runtime": plan.extraction.crewai_runtime,
        "graph_topology": plan.extraction.graph_topology,
        "langchain_runtime": plan.extraction.langchain_runtime,
        "framework_compatibility": _compatibility_data(plan),
        "boundary": "This migration ports the agent identity layer, not the full runtime implementation.",
    }
    write("conversion_map.json", json.dumps(conversion, indent=2))
    write("TODO_MANUAL_REVIEW.md", _manual_review(plan))
    return generated


def _agent_yaml(plan: PortPlan) -> str:
    preferred = "openrouter:openai/gpt-4o-mini"
    if plan.extraction.model_preferences:
        preferred = plan.extraction.model_preferences[0].text
    tool_names = list(dict.fromkeys(_slug(tool.name) for tool in plan.extraction.tools))
    skills = ["ported-identity"] if plan.extraction.identity_fragments else []
    lines = [
        'spec_version: "0.1.0"',
        f"name: {_slug(plan.name)}",
        'version: "0.1.0"',
        f'description: "GitAgent identity port generated from a {plan.framework.framework} source repo."',
        "model:",
        f'  preferred: "{_escape(preferred)}"',
        "  constraints:",
        "    temperature: 0.2",
        "tools:",
    ]
    lines.extend([f"  - {name}" for name in tool_names] or ["  []"])
    lines.append("skills:")
    lines.extend([f"  - {name}" for name in skills] or ["  []"])
    lines.extend(
        [
            "tags:",
            "  - gitagent",
            "  - ported-agent",
            f"  - {plan.framework.framework}",
        ]
    )
    return "\n".join(lines)


def _soul(plan: PortPlan) -> str:
    parts = [
        f"# {plan.name} Soul",
        "",
        "This GitAgent identity was generated by AgentPort from a source framework agent repository.",
        "",
        "AgentPort ports the agent identity layer: prompts, roles, rules, constraints, model preferences, tool metadata, and high-level workflows.",
        "",
        "It does not port or execute framework-specific runtime implementation.",
        "",
        "## Extracted Identity",
    ]
    for fragment in plan.extraction.identity_fragments[:40]:
        parts.extend(["", f"### {fragment.name}", f"Source: `{fragment.source}`", "", fragment.text])
    if not plan.extraction.identity_fragments:
        parts.append("\nNo explicit prompt/persona fragments were detected.")
    return "\n".join(parts)


def _rules(plan: PortPlan) -> str:
    parts = [
        "# Rules",
        "",
        "- Treat generated files as an identity-layer port, not runtime equivalence.",
        "- Do not execute source repository code unless a human explicitly approves it.",
        "- Do not copy secrets, credentials, or deployment-specific wiring into the GitAgent repo.",
        "- Keep framework-specific runtime logic in manual review notes.",
    ]
    for rule in plan.extraction.rules[:40]:
        parts.extend(["", f"## {rule.name}", f"Source: `{rule.source}`", "", rule.text])
    return "\n".join(parts)


def _duties(plan: PortPlan) -> str:
    rows = ["| Source Role | GitAgent Duty | Source |", "|---|---|---|"]
    for item in plan.extraction.hierarchy:
        rows.append(f"| {item.get('name', 'source-agent')} | Preserve source identity and review runtime mapping. | `{item.get('source', '')}` |")
    if len(rows) == 2:
        rows.append("| Ported agent | Follow extracted identity and generated rules. | deterministic extraction |")
    return "\n".join(
        [
            "# Duties",
            "",
            "This file maps source agent roles to GitAgent duties.",
            "",
            *rows,
            "",
            "## Separation Of Duties",
            "",
            "- Generated identity must be validated before registry or publish readiness is claimed.",
            "- Manual review items must be resolved before runtime equivalence is claimed.",
        ]
    )


def _memory(plan: PortPlan) -> str:
    return "\n".join(
        [
            "# Memory",
            "",
            f"- Source repository: `{plan.source_path}`",
            f"- Detected framework: `{plan.framework.framework}` ({plan.framework.confidence:.2f})",
            "- Port boundary: identity layer only.",
        ]
    )


def _workflow(plan: PortPlan) -> str:
    prompts = [
        "Review SOUL.md, RULES.md, DUTIES.md, and conversion_map.json.",
    ]
    prompts.extend(_crewai_workflow_prompts(plan))
    prompts.extend(_langgraph_workflow_prompts(plan.extraction.graph_topology))
    if not plan.extraction.graph_topology:
        prompts.append("If graph_topology is present, compare nodes and edges against the source framework graph before translating runtime behavior.")
    prompts.extend(
        [
            "Resolve TODO_MANUAL_REVIEW.md before claiming runtime equivalence.",
            "Run GitAgent validation before publishing or registry submission.",
        ]
    )
    lines = [
        "name: ported-identity-review",
        "description: Review generated identity files and resolve manual migration items.",
        "steps:",
    ]
    lines.extend(f"  - prompt: {_quoted(prompt)}" for prompt in prompts)
    lines.append("channel: chat")
    return "\n".join(lines)


def _crewai_workflow_prompts(plan: PortPlan) -> list[str]:
    if plan.framework.framework != "crewai":
        return []
    prompts: list[str] = []
    for fragment in plan.extraction.identity_fragments:
        if fragment.kind != "task_context":
            continue
        prompts.append(f"Review CrewAI task context evidence from {fragment.source}: {fragment.text}; preserve ordering as workflow evidence only.")
    return prompts[:40]


def _langgraph_workflow_prompts(topology: dict[str, Any]) -> list[str]:
    if not topology:
        return []
    prompts = [
        "Review LangGraph topology evidence from conversion_map.json; this workflow preserves review evidence only and does not claim runtime conversion.",
    ]
    source_files = topology.get("source_files")
    if isinstance(source_files, list) and source_files:
        prompts.append(f"Confirm LangGraph source files: {', '.join(str(item) for item in source_files[:8])}.")

    state_schemas = topology.get("state_schemas")
    if isinstance(state_schemas, list):
        for schema in state_schemas[:12]:
            if not isinstance(schema, dict):
                continue
            name = schema.get("name") or "unknown"
            fields = schema.get("fields")
            if isinstance(fields, list) and fields:
                field_names = ", ".join(str(field.get("name", "field")) for field in fields if isinstance(field, dict))
                prompts.append(f"Review LangGraph state schema '{name}' fields: {field_names}.")
            else:
                prompts.append(f"Review LangGraph state schema '{name}' and graph variables before any runtime translation.")

    nodes = topology.get("nodes")
    if isinstance(nodes, list):
        for node in nodes[:40]:
            if not isinstance(node, dict):
                continue
            name = node.get("name") or "unknown"
            handler = node.get("handler") or "inline/unknown handler"
            source = _source_location(node)
            prompts.append(f"Review LangGraph node '{name}' handled by '{handler}'{source}; map identity duties only unless runtime conversion is explicitly approved.")

    edges = topology.get("edges")
    if isinstance(edges, list):
        for edge in edges[:40]:
            if not isinstance(edge, dict):
                continue
            source_node = edge.get("source") or "unknown"
            target_node = edge.get("target") or "unknown"
            source = _source_location(edge)
            prompts.append(f"Review LangGraph edge '{source_node} -> {target_node}'{source}; preserve routing as manual-review workflow evidence.")

    conditional_edges = topology.get("conditional_edges")
    if isinstance(conditional_edges, list):
        for edge in conditional_edges[:30]:
            if not isinstance(edge, dict):
                continue
            source_node = edge.get("source") or "unknown"
            router = edge.get("router") or "unknown router"
            path_map = edge.get("path_map")
            routes = _route_summary(path_map) if isinstance(path_map, dict) else "no static path map"
            source = _source_location(edge)
            prompts.append(f"Review LangGraph conditional edge from '{source_node}' via '{router}'{source}; static routes: {routes}.")

    compile_calls = topology.get("compile_calls")
    if isinstance(compile_calls, list):
        for compile_call in compile_calls[:12]:
            if not isinstance(compile_call, dict):
                continue
            call = compile_call.get("call") or "compile"
            source = _source_location(compile_call)
            prompts.append(f"Review LangGraph compile call '{call}'{source}; compiled runtime behavior remains outside the identity-layer port.")

    runtime_markers = topology.get("runtime_markers")
    if isinstance(runtime_markers, list):
        for marker in runtime_markers[:20]:
            if not isinstance(marker, dict):
                continue
            kind = marker.get("kind") or "runtime_marker"
            value = marker.get("value") or marker.get("call") or ""
            source = _source_location(marker)
            prompts.append(f"Review LangGraph runtime marker '{kind}: {value}'{source}; keep runtime-specific behavior in manual review.")

    return prompts


def _source_location(item: dict[str, Any]) -> str:
    source = item.get("file") or item.get("source")
    line = item.get("line")
    if source and line:
        return f" from {source}:{line}"
    if source:
        return f" from {source}"
    return ""


def _route_summary(path_map: dict[Any, Any]) -> str:
    if not path_map:
        return "no static path map"
    return ", ".join(f"{key} -> {value}" for key, value in list(path_map.items())[:12])


def _source_knowledge(plan: PortPlan) -> str:
    evidence = "\n".join(f"- {item}" for item in plan.framework.evidence)
    profile = plan.compatibility.profile if plan.compatibility else "unknown"
    profile_evidence = "\n".join(f"- {item}" for item in (plan.compatibility.evidence if plan.compatibility else []))
    versions = "\n".join(f"- {item}" for item in (plan.compatibility.version_hints if plan.compatibility else []))
    docs = "\n".join(f"- {link['label']}: {link['url']}" for link in (plan.docs_evidence.links if plan.docs_evidence else []))
    return "\n".join(
        [
            f"# Source Framework: {plan.framework.framework}",
            "",
            f"Confidence: {plan.framework.confidence:.2f}",
            f"Compatibility profile: `{profile}`",
            "",
            "## Evidence",
            "",
            evidence or "- No evidence captured.",
            "",
            "## Compatibility Evidence",
            "",
            profile_evidence or "- No compatibility profile evidence captured.",
            "",
            "## Version Hints",
            "",
            versions or "- No dependency version hints found.",
            "",
            "## Documentation Links",
            "",
            docs or "- No preloaded documentation links found.",
        ]
    )


def _tool_yaml(tool: Any) -> str:
    schema = json.dumps(tool.parameters or {"type": "object", "properties": {}})
    return "\n".join(
        [
            f"name: {_slug(tool.name)}",
            f'description: "{_escape(tool.description)}"',
            "version: 1.0.0",
            f"input_schema: {schema}",
            "annotations:",
            "  requires_confirmation: true",
            "  read_only: false",
            "  cost: none",
        ]
    )


def _identity_skill(plan: PortPlan) -> str:
    return "\n".join(
        [
            "---",
            "name: ported-identity",
            'description: "Use extracted source identity evidence from an AgentPort migration."',
            "---",
            "",
            "# Ported Identity",
            "",
            "Use this skill when answering as the migrated agent identity.",
            "",
            "## Source Boundary",
            "",
            "This skill contains portable identity evidence only. Runtime framework behavior remains subject to manual review.",
            "",
            "## Evidence",
            "",
            *[f"- `{f.source}` {f.kind}: {f.name}" for f in plan.extraction.identity_fragments[:80]],
        ]
    )


def _manual_review(plan: PortPlan) -> str:
    lines = [
        "# Manual Review",
        "",
        "This migration ports the agent identity layer, not the full runtime implementation.",
        "",
        "Review these items before claiming runtime equivalence:",
        "",
    ]
    items = plan.extraction.manual_review[:200]
    if not items:
        lines.append("- No runtime-specific issues were detected by the deterministic scanner.")
    else:
        lines.extend(f"- {item}" for item in items)
    return "\n".join(lines)


def _compatibility_data(plan: PortPlan) -> dict[str, object]:
    framework = plan.framework.framework
    supported: list[str] = []
    manual: list[str] = []
    if framework == "crewai":
        supported = [
            "agents.yaml role/goal/backstory",
            "tasks.yaml description/expected_output/string guardrail",
            "Agent(...)/Task(...) literal identity fields",
            "@agent/@task/@crew decorator markers",
            "static tool references",
        ]
        manual = [
            "Crew/process orchestration",
            "hierarchical manager behavior",
            "function guardrails",
            "output_json/output_pydantic runtime validation",
            "async_execution/context wiring",
        ]
    elif framework == "langchain":
        supported = [
            "legacy AgentExecutor/initialize_agent markers",
            "modern create_*_agent factory markers",
            "PromptTemplate and ChatPromptTemplate static prompt text",
            "@tool decorated function metadata",
            "prompt/instruction constants",
            "static tool references",
        ]
        manual = [
            "agent execution loop",
            "tool function implementation",
            "retriever/vectorstore behavior",
            "callback/runtime configuration",
        ]
    elif framework == "langgraph":
        supported = [
            "StateGraph import detection",
            "prompt/instruction constants",
            "add_node/add_edge/add_conditional_edges topology evidence",
            "model constants",
        ]
        manual = [
            "state schema behavior",
            "node execution functions",
            "conditional routing semantics",
            "Command/Send runtime behavior",
            "checkpointing/store/memory",
        ]
    elif framework == "claude-cursor":
        supported = [
            "CLAUDE.md",
            ".claude/CLAUDE.md",
            "CLAUDE.local.md",
            "CLAUDE.md @imports",
            ".cursorrules",
            ".cursor/rules/*.mdc with frontmatter",
        ]
        manual = [
            "Claude local/user/global memories outside source repo",
            "Cursor rule activation semantics",
            "editor-specific runtime enforcement",
        ]
    else:
        supported = ["generic prompt, Markdown, YAML, JSON, and Python literal extraction"]
        manual = ["framework-specific runtime behavior"]
    return {
        "framework": framework,
        "profile": plan.compatibility.profile if plan.compatibility else f"{framework}-generic",
        "profile_confidence": plan.compatibility.confidence if plan.compatibility else plan.framework.confidence,
        "profile_evidence": plan.compatibility.evidence if plan.compatibility else [],
        "version_hints": plan.compatibility.version_hints if plan.compatibility else [],
        "deprecated_patterns": plan.compatibility.deprecated_patterns if plan.compatibility else [],
        "unknown_patterns": plan.compatibility.unknown_patterns if plan.compatibility else [],
        "docs_evidence": plan.docs_evidence.__dict__ if plan.docs_evidence else None,
        "supported_fields": supported,
        "manual_review_fields": manual,
        "identity_fragments": len(plan.extraction.identity_fragments),
        "rules": len(plan.extraction.rules),
        "tools": len(plan.extraction.tools),
        "manual_review_items": len(plan.extraction.manual_review),
    }


def _slug(value: str) -> str:
    slug = "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug or "tool"


def _escape(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")[:500]


def _quoted(value: str) -> str:
    return json.dumps(str(value).replace("\n", " ")[:1000])
